_wandb:
    value:
        cli_version: 0.22.2
        e:
            ps1h6agzt13pkq4iw5mijqq7prrhwsjq:
                args:
                    - run=proposed-Small-CNN-1.2M-CIFAR-10
                    - results_dir=.research/iteration1
                    - mode=full
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "982240026624"
                        used: "921461030912"
                email: gengaru617science@gmail.com
                executable: /home/toma/t-80-8-b-03/_work/airas-20251023-075135-matsuzawa/airas-20251023-075135-matsuzawa/.venv/bin/python3
                git:
                    commit: 7fcc524adbb258eccac48464bfaa98e6e7eade6a
                    remote: https://github.com/auto-res2/airas-20251023-075135-matsuzawa
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-34a823fd-fe55-3d7f-b7da-c2e00d034b28
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-086e9ca0-d470-4051-3339-2049935873bf
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-96c83d7a-e8ec-c6d9-d428-9b84475c8c11
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-673f39a8-0a5b-4036-e360-b50b41e5a6e6
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-bf63367d-1e5e-ad17-b331-7b73497d41c5
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-55a759e4-0595-4df3-c9c7-0add52794ffc
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-888adbff-c09d-59f7-2cae-dc56ac048979
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-5956ff66-3647-b84e-e873-606ed40965d2
                host: t-80-8-b-03
                memory:
                    total: "2151672807424"
                os: Linux-5.15.0-119-generic-x86_64-with-glibc2.35
                program: -m src.train
                python: CPython 3.11.13
                root: /home/toma/t-80-8-b-03/_work/airas-20251023-075135-matsuzawa/airas-20251023-075135-matsuzawa/.research/iteration1
                startedAt: "2025-10-23T08:41:40.356346Z"
                writerId: ps1h6agzt13pkq4iw5mijqq7prrhwsjq
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 50
                - 53
            "2":
                - 1
                - 5
                - 35
                - 41
                - 50
                - 53
            "3":
                - 2
                - 5
                - 14
                - 16
                - 62
            "4": 3.11.13
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
mode:
    value: full
results_dir:
    value: .research/iteration1
run:
    value:
        dataset:
            name: cifar10
            test_split: 10000
            train_split: 45000
            transforms:
                - RandomCrop:
                    padding: 4
                    size: 32
                - RandomHorizontalFlip:
                    p: 0.5
                - ToTensor: {}
                - Normalize:
                    mean:
                        - 0.4914
                        - 0.4822
                        - 0.4465
                    std:
                        - 0.2023
                        - 0.1994
                        - 0.201
            val_split: 5000
        method:
            acquisition_function: expected_improvement
            beta: 0.25
            compression_formula: u(x,t) = s(r(x,t); m0,g0) - beta * log(1 + C(x,t))
            name: BOIL-C
            seeds:
                - 0
                - 1
                - 2
                - 3
                - 4
            surrogate:
                kernel: matern52
                noise: 0.001
                type: gaussian_process
            type: proposed
        model:
            activation: relu
            conv_layers:
                - kernel_size: 3
                  out_channels: 64
                  padding: 1
                  stride: 1
                - kernel_size: 3
                  out_channels: 128
                  padding: 1
                  stride: 1
                - kernel_size: 3
                  out_channels: 256
                  padding: 1
                  stride: 1
                - kernel_size: 3
                  out_channels: 256
                  padding: 1
                  stride: 1
            dropout: 0.25
            fc_layers:
                - out_features: 512
            name: Small-CNN-1.2M
            num_parameters: 1200000
        optuna:
            direction: maximize
            n_trials: 60
            pruner: median
            sampler: tpe
            search_space:
                batch_size:
                    choices:
                        - 32
                        - 64
                        - 128
                    type: categorical
                dropout:
                    high: 0.5
                    low: 0
                    type: uniform
                learning_rate:
                    high: 0.1
                    low: 0.0001
                    type: loguniform
        resources:
            gpu_type: A100
            gpus_per_trial: 1
            time_budget_hours: 8
        run_id: proposed-Small-CNN-1.2M-CIFAR-10
        training:
            batch_size: 64
            checkpoint_interval_epochs: 1
            epochs: 200
            learning_rate: 0.01
            lr_schedule: cosine
            momentum: 0.9
            optimizer: sgd
            weight_decay: 0.0005
trial_limited_batches:
    value: 2
wandb:
    value:
        entity: gengaru617-personal
        mode: online
        project: 251023-test
